### ISSUE TITLE
.close() doesn’t exist? 

### ISSUE THREAD

**Issue by KillzoneKid** [arduino-libraries/AudioZero#22]
https://github.com/arduino-libraries/AudioZero/blob/1e3d3573e13b35eb8235af56bcfdcd9494f0da3d/examples/SimpleAudioPlayerZero/SimpleAudioPlayerZero.ino#L59

Cannot find .close() method, maybe typo and .end() was meant?

**Comment by KillzoneKid** [comment]
Yes, example compile fails, it is all in the test log, it says there in black and white, close() does not exist. It has been failing since forever, why no one checks the quality of commits?

**Comment by CptHolzschnauz** [comment]
I think they meant AudioZero.end()

**Comment by aentinger** [comment]
Fixed via #29 .
