### ISSUE TITLE
not working, cpu restated

### ISSUE THREAD

**Issue by bobricius** [arduino-libraries/AudioZero#3]
Hi, I have custom board with AtSamD21G18.
SD card reading and writing working.
code is restarted somewere near   AudioZero.begin...

**Comment by agdl** [comment]
@bobricius are you using a watch dog? Do you use the same timer of this library for some reason?

**Comment by bobricius** [comment]
No, I am using only example + Usb serial.

**Comment by bobricius** [comment]
Finaly I found problem !!!!! On my cpu I forgot connect VDDANA .... all works but ... DAC restart cpu.
